[project]
authors = ["Tassos Manganaris <tassos.manganaris@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "corallab-policies"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.10.15,<4"

[pypi-dependencies]
corallab-policies = { path = ".", editable = true }
corallab-lib = { git = "https://github.com/Tass0sm/corallab-lib.git", tag = "v0.2" }