[project]
authors = ["Tassos Manganaris <tassos.manganaris@gmail.com>"]
channels = ["conda-forge"]
description = "Common API to many RL / IL policies using various architectures and training algorithms."
name = "corallab-policies"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.10.15,<4"

[pypi-dependencies]
corallab-policies = { path = ".", editable = true }
corallab-lib = { git = "https://github.com/Tass0sm/corallab-lib.git", tag = "v0.2.1" }
matplotlib = ">=3.9.2, <4"
tqdm = ">=4.66.5, <5"

[feature.openai-baselines.pypi-dependencies]
# baselines = { path = "/home/tassos/phd/research/second-project/baselines" }

[feature.torchrl.pypi-dependencies]
torchrl = "*"
mujoco = ">=3.1.1, <3.1.2"
gymnasium = ">=1.0.0a2"
imageio = ">=2.35.1, <3"

[feature.robomimic.pypi-dependencies]
robomimic = { path = "/home/tassos/phd/research/robomimic", editable = true }
robosuite = { path = "/home/tassos/phd/research/robosuite", editable = true }
mujoco = ">=3.1.1, <3.1.2"
numba = ">=0.60.0, <0.61"

# [feature.stable-baselines.pypi-dependencies]
# stable-baselines3 = ">=2.3,<3"

[environments]
default = { solve-group = "default" }
openai-baselines = { features = ["openai-baselines"], solve-group = "default" }
torchrl = { features = ["torchrl"], solve-group = "default" }
robomimic = { features = ["robomimic"], solve-group = "default" }
# stable-baselines = { features = ["stable-baselines"], solve-group = "default" }
